INSERT INTO ETUDIANT (ID, ABSENCES, NOM, PRENOM) VALUES (1, 0, 'john', 'doe');
INSERT INTO ETUDIANT_MODULE (etudiants_ID, modules_ID) VALUES (1, 2);
INSERT INTO MODULE (ID, NOM) VALUES (2, 'mi-4');
INSERT INTO NOTE (ID, VALEUR, ETUDIANT_ID, MODULE_ID) VALUES (51, 23.00000, 1, 2);
INSERT INTO NOTE (ID, VALEUR, ETUDIANT_ID, MODULE_ID) VALUES (101, 4.00000, 1, 2);
INSERT INTO NOTE (ID, VALEUR, ETUDIANT_ID, MODULE_ID) VALUES (151, 76.00000, 1, 2);
INSERT INTO SEQUENCE (SEQ_NAME, SEQ_COUNT) VALUES ('SEQ_GEN', 200);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'ETUDIANT', 'ETUDIANT', 2, 'CREATE TABLE ETUDIANT (ID NUMBER(10) NOT NULL, ABSENCES NUMBER(10) NOT NULL, NOM VARCHAR NOT NULL, PRENOM VARCHAR NOT NULL, PRIMARY KEY (ID))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_ETUDIANT_1', 'ETUDIANT', 3, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'MODULE', 'MODULE', 4, 'CREATE TABLE MODULE (ID NUMBER(10) NOT NULL, NOM VARCHAR NOT NULL UNIQUE, PRIMARY KEY (ID))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_MODULE_1', 'MODULE', 5, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_MODULE_2', 'MODULE', 6, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'NOTE', 'NOTE', 7, 'CREATE TABLE NOTE (ID NUMBER(10) NOT NULL, VALEUR NUMBER(12,5) NOT NULL, ETUDIANT_ID NUMBER(10) NOT NULL, MODULE_ID NUMBER(10) NOT NULL, PRIMARY KEY (ID))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_NOTE_1', 'NOTE', 8, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'ETUDIANT_MODULE', 'ETUDIANT_MODULE', 9, 'CREATE TABLE ETUDIANT_MODULE (etudiants_ID NUMBER(10) NOT NULL, modules_ID NUMBER(10) NOT NULL, PRIMARY KEY (etudiants_ID, modules_ID))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_ETUDIANT_MODULE_1', 'ETUDIANT_MODULE', 10, null);
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('table', 'SEQUENCE', 'SEQUENCE', 11, 'CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMBER(19), PRIMARY KEY (SEQ_NAME))');
INSERT INTO sqlite_master (type, name, tbl_name, rootpage, sql) VALUES ('index', 'sqlite_autoindex_SEQUENCE_1', 'SEQUENCE', 12, null);